import web3 from './web3';

const abi = [
  {
    inputs: [],
    stateMutability: 'nonpayable',
    type: 'constructor',
    constant: undefined,
    payable: undefined,
    signature: 'constructor',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'index', type: 'uint256' }],
    name: 'approveClaim',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0x46e30135',
  },
  {
    inputs: [
      { internalType: 'string', name: 'dreamJob', type: 'string' },
      { internalType: 'string', name: 'purpose', type: 'string' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'uint256', name: 'value', type: 'uint256' },
      { internalType: 'address', name: 'recipient', type: 'address' },
    ],
    name: 'claim',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0xec729859',
  },
  {
    inputs: [],
    name: 'claiming',
    outputs: [
      { internalType: 'string', name: 'dreamJob', type: 'string' },
      { internalType: 'string', name: 'purpose', type: 'string' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'uint256', name: 'value', type: 'uint256' },
      { internalType: 'address', name: 'claimer', type: 'address' },
      { internalType: 'address', name: 'recipient', type: 'address' },
      { internalType: 'bool', name: 'done', type: 'bool' },
      {
        internalType: 'uint256',
        name: 'approvedCounts',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x0defc08a',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'claims',
    outputs: [
      { internalType: 'string', name: 'dreamJob', type: 'string' },
      { internalType: 'string', name: 'purpose', type: 'string' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'uint256', name: 'value', type: 'uint256' },
      { internalType: 'address', name: 'claimer', type: 'address' },
      { internalType: 'address', name: 'recipient', type: 'address' },
      { internalType: 'bool', name: 'done', type: 'bool' },
      {
        internalType: 'uint256',
        name: 'approvedCounts',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0xa888c2cd',
  },
  {
    inputs: [
      { internalType: 'string', name: 'nickName', type: 'string' },
      { internalType: 'uint256', name: 'latitude', type: 'uint256' },
      { internalType: 'uint256', name: 'longitude', type: 'uint256' },
    ],
    name: 'contribute',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
    constant: undefined,
    payable: true,
    signature: '0x64f745a7',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'contributors',
    outputs: [
      { internalType: 'string', name: 'nickName', type: 'string' },
      { internalType: 'address', name: 'place', type: 'address' },
      { internalType: 'uint256', name: 'latitude', type: 'uint256' },
      { internalType: 'uint256', name: 'longitude', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x3cb5d100',
  },
  {
    inputs: [],
    name: 'getContributors',
    outputs: [
      {
        components: [
          { internalType: 'string', name: 'nickName', type: 'string' },
          { internalType: 'address', name: 'place', type: 'address' },
          {
            internalType: 'uint256',
            name: 'latitude',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'longitude',
            type: 'uint256',
          },
        ],
        internalType: 'struct Appetito.ContibutorType[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0xaf157c19',
  },
  {
    inputs: [],
    name: 'getContributorsNum',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x39e77905',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x8da5cb5b',
  },
  {
    inputs: [],
    name: 'population',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x78880f4a',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'index', type: 'uint256' }],
    name: 'startStudy',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
    constant: undefined,
    payable: true,
    signature: '0xa5f7542a',
  },
];

const address = '0xa8E565e0FC9eeA5f06c1dDD54a8e4476101006a7';

export default new web3.eth.Contract(abi, address);
// export default appetitoInstanceCopy;
